---
- name: Check if ansible version is equal or greater than 2.11
  ansible.builtin.fail:
    msg: "Ansible core should be equal or greater than 2.11"
  when: ansible_version.full is ansible.builtin.version('2.11','<')

- name: Check if python is equal or greater than 3
  ansible.builtin.fail:
    msg: "Python should be equal or greater than 3"
  when: ansible_python.version.major is ansible.builtin.version('3','<')

- name: Edit /etc/subuid file
  ansible.builtin.template:
    dest: "{{ item.path }}"
    src: "{{ libvirt_templates_dir }}/subids.j2"
  loop: "{{ lxd_subids }}"
  when: lxd_subids is defined and lxd_subids | length > 0
  tags: libvirt_define,subids

- name: Create libvirt defined VMs
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'vm-template.xml.j2') }}"
    autostart: "{{ vm.autostart | default(false) }}" 
    state: "{{ vm.state | default(shutdown) }}"
  loop: "{{ libvirt_libvirt_vms }}"
  loop_control:
    loop_var: vm
  when: libvirt_libvirt_vms is defined and libvirt_libvirt_vms | length > 0
  tags: libvirt_define,libvirt_libvirt_vms

- name: Create lxd defined VMs/containers
  ansible.builtin.import_tasks: lxd.yml
  when: libvirt_lxd_hosts is defined and libvirt_lxd_hosts | length > 0
  tags: libvirt_define,libvirt_lxd_vms

- name: Create proxmox VMs/containers if defined
  ansible.builtin.import_tasks: proxmox.yml
  when: libvirt_proxmox_hosts is defined and libvirt_proxmox_hosts | length > 0
  tags: libvirt_define,libvirt_proxmox_vms
