---
- name: Install LXD on Gentoo Linux
  community.general.portage:
    package: "{{ libvirt_packages }}"
    state: present
  tags: lxd_install
  notify:
    - Enable lxd

- name: Start lxd service after installation
  ansible.builtin.service:
    name: lxd
    state: started
  tags: lxd_install,lxd_start
