---

- name: install LXD on Gentoo Linux
  portage:
    package: "{{ libvirt_packages }}"
    state: present
  tags: lxd_install
  notify:
    - enable lxd

- name: start lxd service after installation
  service:
    name: lxd
    state: started
  tags: lxd_install,lxd_start
