---
# Install VMs/containers on proxmox host/cluster
# install proxmox packages on Debian
- name: Check if distr is Debian
  ansible.builtin.debug:
    msg: "Distr is {{ ansible_distribution }}, not Debian"
  when: ansible_distribution != 'Debian'
  failed_when: ansible_distribution != 'Debian'

- name: Install proxmox packages on Debian
  when: proxmox_install_force is defined and proxmox_install_force | bool
  block:
    - name: Add gpg key into system
      ansible.builtin.apt_key:
        url: "{{ proxmox_apt_repos.gpg }}"
        state: "present"
      tags: proxmox,proxmox_install
    - name: Add proxmox repos
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        filename: "proxmox"
        state: "present"
      loop: "{{ proxmox_apt_repos.repos }}"
      tags: proxmox,proxmox_install
    - name: Upgrade system
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
      tags: proxmox,proxmox_install
    - name: Install pve-qemu-kvm
      ansible.builtin.apt:
        name: "pve-qemu-kvm"
      tags: proxmox,proxmox_install
    - name: Install all pve packages
      ansible.builtin.apt:
        name: "{{ proxmox_apt_packages }}"
      tags: proxmox,proxmox_install
