---
- name: Enable lxd
  ansible.builtin.service:
    name: lxd
    enabled: true

- name: Disable lxd
  ansible.builtin.service:
    name: lxd
    enabled: false

- name: Start lxd
  ansible.builtin.service:
    name: lxd
    state: started

- name: Restart lxd
  ansible.builtin.service:
    name: lxd
    state: restarted

- name: Reload lxd
  ansible.builtin.service:
    name: lxd
    state: reloaded

- name: Stop lxd
  ansible.builtin.service:
    name: lxd
    state: stopped

- name: Enable lxd-dns
  ansible.builtin.service:
    name: lxd-dns-{{ lxd_network_bridge }}
    enabled: true

- name: Start lxd-dns
  ansible.builtin.service:
    name: lxd-dns-{{ lxd_network_bridge }}
    state: started

- name: Restart lxd-dns
  ansible.builtin.service:
    name: lxd-dns-{{ lxd_network_bridge }}
    state: restarted
