---

- name: enable lxd
  service:
    name: lxd
    enabled: yes
  
- name: disable lxd
  service:
    name: lxd
    enabled: no
  
- name: start lxd
  service:
    name: lxd
    state: started
  
- name: restart lxd
  service:
    name: lxd
    state: restarted
  
- name: reload lxd
  service:
    name: lxd
    state: reloaded
  
- name: stop lxd
  service:
    name: lxd
    state: stopped
  
